default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dweedo_development
test:
  <<: *default
  database: dweedo_test
production:
  <<: *default
  database: dweedo_production
  username: dweedo
  password: <%= ENV['DWEEDO_DATABASE_PASSWORD'] %>
